services:
  frontend:
    build:
      context: .
      target: prod
      args:
        VITE_API_URL: "http://localhost:30000"
    container_name: upload-image-cont
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: false
